/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package lennie.org.lennie.swig;

public class Unix {
  public static SWIGTYPE_p_uid_t getuid() {
    return new SWIGTYPE_p_uid_t(UnixJNI.getuid(), true);
  }

}
