/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lennie_org_lennie_ndk_MyNDK */

#ifndef _Included_lennie_org_lennie_ndk_MyNDK
#define _Included_lennie_org_lennie_ndk_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lennie_org_lennie_ndk_MyNDK
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_lennie_org_lennie_ndk_MyNDK_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
